version: '3'

services:

  elixir_test:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: sh -c "MIX_ENV=test; mix ecto.setup; mix test.watch"
    working_dir: /app/memz
    environment:
      - MIX_ENV=test
      - PORT=4001
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=memz
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./:/app
    ports:
      - "4001:4001"
    links:
      - postgres_test
    depends_on:
      - postgres_test

  postgres_test:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memz_test
    ports:
      - "32784:5432"