version: '3'

services:

  elixir:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app/memz
    command: sh -c "mix ecto.setup; mix phx.server"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=memz
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memz
    ports:
      - "32783:5432"